finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('registers.urls')),
    path('', include('reports.urls')),
    path('admin/', admin.site.urls),
]

registers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register/expense", views.register_expense,
         name="register_expense"),
    path("register/sucess", views.expense_success, name="expense_success"),
    path("register/income", views.register_income,
         name="register_income"),
]

registers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    CATEGORY_TYPES = [
        ('income', 'Income'),
        ('expense', 'Expense'),
    ]
    type = models.CharField(max_length=10, choices=CATEGORY_TYPES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class PaymentMethod(models.Model):
    name = models.CharField(max_length=100)
    start_billing_day = models.IntegerField(
        help_text="Day of the month when billing starts")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Installment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_installments = models.IntegerField()
    start_date = models.DateField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, limit_choices_to={'type': 'expense'})
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.description} - Total: {self.total_amount} ({self.total_installments} installments)"


class RecurringExpense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    start_date = models.DateField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, limit_choices_to={'type': 'expense'})
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.description} - Total: {self.total_amount} "


class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, limit_choices_to={'type': 'expense'})
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.SET_NULL, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    installment_plan = models.ForeignKey(
        Installment, on_delete=models.CASCADE, null=True, blank=True, related_name='expenses')
    reccurring_expense = models.ForeignKey(
        RecurringExpense, on_delete=models.CASCADE, null=True, blank=True, related_name='recurring_expenses')

    def __str__(self):
        return f"{self.description} - {self.category} - {str(self.amount)}"


class Income(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, limit_choices_to={'type': 'income'}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.description} - {str(self.amount)}"


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    investment_type = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.description} - {str(self.amount)}"

registers/forms.py
from django import forms
from .models import Expense, Income, Category


class ExpenseForm(forms.ModelForm):
    installments = forms.IntegerField(
        min_value=1, initial=1, label='Number of Installments')

    class Meta:
        model = Expense
        fields = ['description', 'amount', 'installments',
                  'date', 'category', 'payment_method']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})

        }

    def __init__(self, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)

        # Order the category field by name
        self.fields['category'].queryset = Category.objects.order_by('name')


class IncomeForm(forms.ModelForm):

    class Meta:
        model = Income
        fields = ['description', 'amount',
                  'date', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})

        }

registers/views.py
from django.shortcuts import render, redirect
from .forms import ExpenseForm, IncomeForm
from .services import ExpenseService, InstallmentService, IncomeService
from django.contrib import messages
# Create your views here.


def register_expense(request):
    if (request.method == 'POST'):
        form = ExpenseForm(request.POST)
        if not form.is_valid():
            return
        expense_data = form.cleaned_data

        user = request.user

        if expense_data['installments'] > 1:
            installment_service = InstallmentService()
            installment_plan, expenses = installment_service.create_installments(
                user, expense_data)
            messages.success(
                request, f"{expense_data['installments']} installments have been registered.")
        else:
            expense_service = ExpenseService()
            expense = expense_service.create_single_expense(
                user, expense_data)
            messages.success(request, "Expense has been registered.")

        return redirect('expense_success')

    else:
        form = ExpenseForm()
    return render(request, 'register/expense_form.html', {'form': form})


def expense_success(request):
    return render(request, 'register/expense_success.html')


def register_income(request):
    if (request.method == 'POST'):
        form = IncomeForm(request.POST)
        if not form.is_valid():
            return
        income_data = form.cleaned_data

        user = request.user

        income_service = IncomeService()
        income = income_service.create_income(user, income_data)

        return redirect('expense_success')

    else:
        form = IncomeForm()
    return render(request, 'register/income_form.html', {'form': form})


def income_success(request):
    return render(request, 'register/income_success.html')

registers/templates/register/expense_form.html
{% extends "core/base.html" %}
{% load custom_filters %}
{% block content %}
    <div class="container mx-auto mt-10 max-w-lg ">
        <h2 class="text-2xl font-bold mb-6 ">Register Expense</h2>
        <form method="post" class="bg-slate-800/40 p-6 rounded-lg shadow-lg">
            {% csrf_token %}
            <div class="mb-4 space-y-2">
                <label for="id_description" class=" text-gray-400">Description</label>
                {{ form.description|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_amount" class=" text-gray-400">Amount</label>
                {{ form.amount|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_installments" class=" text-gray-400">Installments</label>
                {{ form.installments|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_date" class=" text-gray-400">Date</label>
                {{ form.date|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_category" class=" text-gray-400">Category</label>
                {{ form.category|add_class:"w-full px-3 bg-transparent py-2 appearance-none border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 *:bg-slate-900" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_payment_method" class=" text-gray-400">Payment Method</label>
                {{ form.payment_method|add_class:"w-full px-3 bg-transparent py-2 appearance-none border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 *:bg-slate-900" }}
            </div>
            <button type="submit"
                    class="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-700">Submit</button>
        </form>
    </div>
{% endblock content %}

registers/templates/register/expense_success.html
{% extends "core/base.html" %}
{% block content %}
    <div class="flex justify-center items-center h-screen w-full">
        <h2>Expense Registered Successfully!</h2>
    </div>
{% endblock content %}

registers/templates/register/income_form.html
{% extends "core/base.html" %}
{% load custom_filters %}
{% block content %}
    <div class="container mx-auto mt-10 max-w-lg ">
        <h2 class="text-2xl font-bold mb-6 ">Register Income</h2>
        <form method="post" class="bg-slate-800/50 p-6 rounded-lg shadow-lg">
            {% csrf_token %}
            <div class="mb-4 space-y-2">
                <label for="id_description" class=" text-gray-400">Description</label>
                {{ form.description|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_amount" class=" text-gray-400">Amount</label>
                {{ form.amount|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_date" class=" text-gray-400">Date</label>
                {{ form.date|add_class:"w-full px-3 bg-transparent py-2 border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
            </div>
            <div class="mb-4 space-y-2">
                <label for="id_category" class=" text-gray-400">Category</label>
                {{ form.category|add_class:"w-full px-3 bg-transparent py-2 appearance-none border border-slate-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 *:bg-slate-900" }}
            </div>
            <button type="submit"
                    class="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-700">Submit</button>
        </form>
    </div>
{% endblock content %}